### PR TITLE
verify me

### PR DESCRIPTION
**Pull request by akoehn**
> associate 0000-0002-4880-2016 with the author Arne Köhn.

(agy computing, making use of the new agents.md)

> can you make the identifier arne-koehn instead of arne-kohn?

Looks like the AGENTS.md works, agy needed to search a bit through the files to find the correct approach though.

### CODE REVIEW

**Comment by mbollmann** [comment]
Did it honor the request to go through the library for all changes? I see it modified a `people.yaml` which doesn't exist anymore :)

**Comment by akoehn** [comment]
yes yes, I noticed that my `git pull` failed and I started from a severely outdated branch ...

running again at the moment and it is doing way too much (and also finding some problems in the test setup)

with the new branch, it ran this:

```
from acl_anthology import Anthology
from acl_anthology.people import Name

anthology = Anthology.from_within_repo()

person = anthology.people.get('arne-kohn/unverified')
if person is None:
    people = anthology.people.get_by_name(Name('Arne', 'Köhn'))
    if people:
        person = people[0]

if person is None:
    raise ValueError('Could not find person for Arne Köhn')

print(f'Found person: {person.id}')

if not person.is_explicit:
    person.make_explicit('arne-koehn')
elif person.id != 'arne-koehn':
    person.change_id('arne-koehn')

person.orcid = '0000-0002-4880-2016'

anthology.save_all()
print('Saved all successfully!')
```

which seems reasonable to me

then it ran `just check`, which ran into some problems. Will have a look what the problem is

```
Bash(just check)
  ⎿  <output +142 lines>
                  'build', '-b', '/tmp/pdm-build-818lt2r7']' returned non-zero exit status
                  1.

                  hint: This usually indicates a problem with the package or the build
                  environment.
              help: `editdistance` (v0.8.1) was included because `aclanthology-org`
                    (v2026.2.1) depends on `openreview-py` (v2.4.0) which depends on
                    `editdistance`
            make: *** [Makefile:235: test-scripts] Fehler 1
            error: Recipe `check` failed on line 13 with exit code 2
● Bash(UV_PYTHON=3.12 just check)
  ⎿  <output +69 lines>
              /home/arne/development/software/acl-anthology/.venv/lib/python3.12/site-packages/iso639/iso639.py:240: SyntaxWarning: invalid escape sequence '\['
                m = re.findall('\[([a-z]{3})\]', s)

            -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
            =========================== short test summary info ============================
            ERROR tests/test_ingest.py - LookupError:
            !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
            ==================== 2 skipped, 1 warning, 1 error in 4.81s ====================
            make: *** [Makefile:235: test-scripts] Fehler 2
            error: Recipe `check` failed on line 13 with exit code 2
● Bash(UV_PYTHON=3.12 uv run python -c "import nltk; nltk.download('punkt_tab'); nltk.download('punkt')")
  ⎿  [nltk_data] Downloading package punkt_tab to /home/arne/nltk_data...
            [nltk_data]   Unzipping tokenizers/punkt_tab.zip.
            [nltk_data] Downloading package punkt to /home/arne/nltk_data...
            [nltk_data]   Unzipping tokenizers/punkt.zip.
```
and then `just check` worked. After that, it ran `UV_PYTHON=3.12 just python test-integration` which takes quite some time.

**Comment by akoehn** [comment]
@mbollmann should we add instructions what tests are needed when? 

Also, what is the nltk dep? I might look into it later if you don't know from the top of your head

**Comment by mbollmann** [comment]
> Also, what is the nltk dep? I might look into it later if you don't know from the top of your head

Look in the check-build workflow, I think it explicitly installs it. I haven't checked if it's possible to add this to the `pyproject.toml`, it's only for some script in `bin/` and tests that use it, IIRC.

**Comment by mbollmann** [comment]
> @mbollmann should we add instructions what tests are needed when?

Hmm I have told Claude often to skip the integration tests because they take time, so we can add something to that effect if it's not in there yet. Then again, the most appropriate time to run them is after making changes to `data/`.

EDIT: Maybe say they should only be run on explicit request or something, like with the entire website build?

**Comment by mbollmann** [comment]
The editdistance thing definitely works with Python 3.14 btw,  no need to fall back to 3.12, but I've gotten the same error recently and I believe I had to clear out my venv and ensure I was using uv-managed Python, not my system one...

**Comment by akoehn** [comment]
I think the integration tests only need to be run when changing the python code. If only data is changed, we validate against the schema etc.

Below is what gemini proposes analyzing friction in the session.

I think it makes sense to at least go with a different python version for now. Also, punkt should be automatically downloaded if missing.

integration tests should only be run after changing python code and it should note that it is expensive.

documentation for common anthology use cases make sense but I would put them in documentation external to AGENTS.md and only link to it.


### 1. Root Causes of Friction Encountered

  1. .python-version set to 3.14 (C-extension build failures):
      • [.python-version:1](file:///home/arne/development/software/acl-anthology/.python-version#L1) was set to 3.14.
      • When running uv run or just check, uv picked CPython 3.14 by default.
      • Transitive C-extension dependencies (such as editdistance via openreview-py) do not have pre-built binary wheels for Python 3.14 on PyPI yet. Because system development headers
      (Python.h / python3.14-dev) were not installed, source compilation failed immediately.
      • Workaround needed: We had to force UV_PYTHON=3.12 / --python 3.12.
  2. Missing NLTK punkt_tab dataset during just check:
      • just check runs make test-scripts (pytest on tests/).
      • [test_ingest.py](file:///home/arne/development/software/acl-anthology/tests/test_ingest.py) imports [protect.py](file:///home/arne/development/software/acl-anthology/bin/fixedcase/protect.py), which calls nltk.tokenize.word_tokenize().
      • When NLTK's punkt_tab data is not already downloaded in ~/nltk_data, pytest fails during test collection with LookupError: Resource 'punkt_tab' not found.
      • Workaround needed: We had to manually execute nltk.download('punkt_tab').
  3. Missing recipes in [A](file:///home/arne/development/software/acl-anthology/AGENTS.md)[GENTS.md](file:///home/arne/development/software/acl-anthology/AGENTS.md) for Author/Person Operations:
      • [AGENTS.md](file:///home/arne/development/software/acl-anthology/AGENTS.md) has general guidelines and paper ingestion examples, but lacks code recipes for common author maintenance operations (e.g. promoting an unverified author to explicit,
      adding an ORCID, and propagating verified IDs to XML files).
      • This required inspecting [index.py](file:///home/arne/development/software/acl-anthology/python/acl_anthology/people/index.py) and [modifying-data.md](file:///home/arne/development/software/acl-anthology/python/docs/guide/modifying-data.md) to determine whether make_explicit(), PersonIndex.create(), or set_id_on_items() was the intended pattern.
  4. Integration Test Suite Duration:
      • Running the full just python test-integration suite runs 3,445 tests and takes ~7.5 minutes because it roundtrips every single XML collection in the entire Anthology.

  ──────
  ### 2. Recommended Infrastructure Improvements

  1. **Update [.python-version](file:///home/arne/development/software/acl-anthology/.python-version)**:
      • Change .python-version from 3.14 to a stable version with pre-built binary wheels available (e.g. 3.12 or 3.11).
      • In root [pyproject.toml:4](file:///home/arne/development/software/acl-anthology/pyproject.toml#L4), consider restricting requires-python = ">=3.11, <3.14" until dependencies support Python 3.14.
  2. Automate NLTK resource bootstrapping for test suite:
      • Add a root tests/conftest.py fixture or handle lazy downloading in [common.py](file:///home/arne/development/software/acl-anthology/bin/fixedcase/common.py):
        import nltk
        try:
            nltk.data.find("tokenizers/punkt_tab")
        except LookupError:
            nltk.download("punkt_tab", quiet=True)

      • This ensures just check runs out-of-the-box in clean environments or new container instances without manual setup.

  ──────
  ### 3. Recommended [A](file:///home/arne/development/software/acl-anthology/AGENTS.md)[GENTS.md](file:///home/arne/development/software/acl-anthology/AGENTS.md) Improvements

  Add a dedicated "Author and Person Management" section under "Key API patterns":

    ### Author and Person Management

    - **Make an existing unverified author explicit and attach an ORCID**:
      ```python
      from acl_anthology import Anthology
      anthology = Anthology.from_within_repo()

      # Find the unverified author (e.g. by slug or name)
      person = anthology.people.get("first-last/unverified")  # or anthology.people.get_by_name(Name("First", "Last"))[0]

      # Promote to explicit (updates people.json AND adds id="..." to their papers in data/xml/)
      person.make_explicit("canonical-person-id")
      person.orcid = "0000-0002-XXXX-XXXX"

      anthology.save_all()

  • Create a new explicit person without updating XML files:
    from acl_anthology.people import Name
    person = anthology.people.create(
        id="canonical-person-id",
        names=[Name("First", "Last")],
        orcid="0000-0002-XXXX-XXXX",
    )
    anthology.save_all()

  • Merge duplicate author records:
    p2.merge_into(p1)  # moves p2 publications & metadata into p1
    anthology.save_all()



    Also add guidance on **efficient testing scopes**:
    - `just check`: Fast checks (~40s) — validates XML schemas via `jing`, JSON well-formedness, linting/formatting, and unit tests. Run after any `data/` metadata edit.
    - `just python test-integration`: Comprehensive (~7.5m) — roundtrips all collections. Only needed for core library changes or full CI verification.

**Comment by akoehn** [comment]
> The editdistance thing definitely works with Python 3.14 btw, no need to fall back to 3.12, but I've gotten the same error recently and I believe I had to clear out my venv and ensure I was using uv-managed Python, not my system one...

This DID run through uv and it did not work. Maybe you have dev headers installed and it compiled the dependency for you. Or you have something else. `uv run --python cpython-3.14 python -c "import editdistance; print('editdistance works on uv managed 3.14!')"` does not work on my machine.

I will prepare a new PR with some changes to not conflate them with this rather trivial change.

**Comment by mbollmann** [comment]
> I think the integration tests only need to be run when changing the python code. If only data is changed, we validate against the schema etc.

The schema can't catch logical errors that the integration tests will error out on, like using nonexistent IDs or even indenting the XML wrong.

> This DID run through uv and it did not work. Maybe you have dev headers installed and it compiled the dependency for you.

From memory: I had exactly the same errors, also when running through `uv`. I had to use `--isolated --no-managed-python` on the initial call to make it work.

**Comment by akoehn** [comment]
>  The schema can't catch logical errors that the integration tests will error out on, like using nonexistent IDs or even indenting the XML wrong.

but can that break when the data is only changed through the python API (unless we hit a bug in the code)?

**Comment by mbollmann** [comment]
> but can that break when the data is only changed through the python API (unless we hit a bug in the code)?

There are some edge cases where this can happen, yeah, e.g. as recently pointed out here: https://github.com/acl-org/acl-anthology/pull/9820#discussion_r3886698126

Hopefully we will eliminate those blind spots over time, of course.

**Comment by akoehn** [comment]
@mbollmann would you mind approving this PR? I will put agents.md stuff etc in another one.

**Comment by mbollmann** [comment]
Tbh I was wondering what our stance was on “customizing” author IDs, as I honestly can't remember. As a fellow German, I obviously agree that "arne-koehn" is the correct ID to assign, but there's [jorg-tiedemann](https://aclanthology.org/people/jorg-tiedemann/) and [joachim-kohler](https://aclanthology.org/people/joachim-kohler/) and lots of Müllers with -muller IDs... Then again, there are IDs like [thomas-mueller](https://aclanthology.org/people/thomas-mueller/) just because they happened to publish some papers with the "ue" spelling and it got interpreted as  the canonical name. 🫠

In short, I’m happy to approve this, I just don’t want @nschneid to drown in cosmetic ID correction requests. 😅

**Review by mbollmann — APPROVED** [review]

**Comment by akoehn** [comment]
There is also Philipp Köhn ALWAYS publishing under Koehn ;)

So I think I have a strong case not to be discrimiated against just because I was born late enough for unicode

**Comment by nschneid** [comment]
So far there has been no flood of cosmetic person ID requests.

Just for fun I ran the stats on the composition of person IDs:

```py
unverified = name_slug_match = orcid_match = other = 0
for pid,person in anthology.people.items():
        if pid.endswith('/unverified'):
            unverified += 1
        elif person.orcid and person.orcid.lower()[-5:]==pid[-5:]:
            orcid_match += 1
        elif any(n.slugify()==pid for n in person.names):
            name_slug_match += 1
        else:
            other += 1
```

gives

| Status | N |
|-------|----:|
| unverified | 100271 |
| name_slug_match | 31189 |
| orcid_match | 2428 |
| other | 267 |

"other" is mostly institutional suffixes like `-cmu`, but would also include any custom name slug spellings (I think we have some cases derived from incorrect metadata that was later corrected on the paper, e.g. including a middle initial that wasn't in the PDF; as long as it's not an outright typo I don't particularly mind). (EDIT: also includes some names with apostrophes from before we changed the slugification algorithm to replace a smart apostrophe with a hyphen)
